-- Insertion des rôles si ils n'existent pas déjà
INSERT IGNORE INTO role (nom) VALUES ('ROLE_FOURNISSEUR');
INSERT IGNORE INTO role (nom) VALUES ('ROLE_ENSEIGNANT');
INSERT IGNORE INTO role (nom) VALUES ('ROLE_TECHNICIEN');
INSERT IGNORE INTO role (nom) VALUES ('ROLE_RESPONSABLE');
INSERT IGNORE INTO role (nom) VALUES ('ROLE_CHEF_DEPARTEMENT'); 